### ISSUE TITLE
Add support for minting

### ISSUE THREAD

**Issue by meonkeys** [peercoin/docker-peercoind#7]

**Comment by peerchemist** [comment]
Just remove this line before running:
https://github.com/peercoin/docker-peercoind/blob/master/0.9.0/docker-compose.yml#L15

**Comment by meonkeys** [comment]
Ok, that's a start. My wallet is encrypted, so I'll also have to enter the passphrase somehow. I'll try running `peercoin-cli walletpassphrase PASSPHRASE` in the container with `docker exec`.

**Comment by peerchemist** [comment]
Yes, that should handle it.

**Comment by meonkeys** [comment]
Thanks!

After reading https://bitfalls.com/2018/03/11/peercoin-explained-proof-stake-pioneer/ I decided against running peercoind 24x7 since I don't need to for minting. Sounds like I can just start up my desktop client once a month or so to update my wallet and see if I minted any peercoin.

**Comment by sunnyqueen** [comment]
when you start up your client, it will start synchronising (downloading the blocks) until it is done, and than it will be able to mint if the wallet is unlocked for minting. 
Reading how you want to do it i dont think you will see any minted peercoins, unless you leave it on long enough to find a block and mint some. I haven't read the article, maybe they mean you dont have to leave it on 24 hours, but still you have to leave it on several hours until it mints a block, and still you wont see any blocks found from the period the wallet was offline.

**Comment by meonkeys** [comment]
Ok. Another source: https://talk.peercoin.net/t/mint-offline-with-peerunity/3126/13?u=snitok3os . I think you're on track except for the part about coin age. Based on that and the article above it sounds like I could leave it offline for a while and **will** accrue coin age, but I'd need to come online and leave it online every so often to see if anything is minted. I can't say I have a solid complete understanding yet but this much seems clear.

**Comment by sunnyqueen** [comment]
yes your coins will get older day by day, and you will get rewarded when you find a block, but you will only find one when you are online

**Comment by Nagalim** [comment]
You can mint periodically, say leaving the client on for one week a month, and receive a good portion of your rewards.  However, since v0.9 you will be missing out on a substantial portion of rewards if you do not mint 24/7.  There are two parts to the reward, one based on coinage and one based on number of blocks found.  Minting continuously gets both of these rewards, while minting periodically misses a lot of the blocks that it might otherwise have found (and therefore sacrifices some of that portion of the reward).  Minting continuously is the best solution for overall chain security and for the growth of your wealth.
